### ISSUE TITLE
No yml file issue 

### ISSUE THREAD

**Issue by Maahir-Paliwal** [AIRMEC/HECTOR#1]
When following the steps outlines in the README, I copy and pasted the instructions to create the Conda file. When trying to set up the Conda environment it tells me there is no environment.yml file and I therefore cannot proceed with the next steps. Here is the image containing the issue:
<img width="1207" alt="Screenshot 2024-07-04 at 2 50 36 PM" src="https://github.com/AIRMEC/HECTOR/assets/170120102/b5153790-56e2-4bbf-b7dc-653dd9592e60">

**Comment by jjhbw** [comment]
Hi there, good find. We forgot to check in the `environment.yml` file. Thanks for pointing that out. We're looking it up currently on our workstation and will upload when we find it.

In the meantime, you can probably make everything work by simply installing the required dependencies yourself. They are listed at the top of `extract_features.py` and `train.py`. The latest versions of each dependency should work with this code, but let us know if they don't.

**Comment by Maahir-Paliwal** [comment]
Hi! I tried to install the dependencies on my own in a conda environment using all the latest versions of the packages. I ran into a dependency issue when installing nmslib, so I would appreciate the environment.yml file! Thank you so much in advance.

**Comment by jjhbw** [comment]
What kind of error are you running into? If it is an error that occurs during installing the dependency, the environment file may not be able to help.

**Comment by Maahir-Paliwal** [comment]
This is a picture of the error I'm running into when installing nmslib. 
[screenshot2.pdf](https://github.com/user-attachments/files/16130362/screenshot2.pdf)
[screenshot1.pdf](https://github.com/user-attachments/files/16130363/screenshot1.pdf)

**Comment by jjhbw** [comment]
I'm afraid that's an issue that we can't help with… It seems like your machine cannot install nmslib for some reason. Maybe take a look at the nmslib issue tracker. I see a few issues there related to installation failing.

**Comment by Maahir-Paliwal** [comment]
I'll look into that more. Thank you! Would you as well please notify me when you've uploaded the environment.yml file? Thank you for your time and help!

**Comment by jjhbw** [comment]
Uploaded now. Sorry for the confusion. Hope you got it to work in the meantime.
