### ISSUE TITLE
Clarification on Pretraining Implementation Using Data

### ISSUE THREAD

**Issue by shady0501** [AIRMEC/HECTOR#3]
Dear authors,

Thank you for sharing this remarkable work! I have read your paper and reviewed parts of the code with great interest. I noticed that the paper mentions pretraining using data from 1,862 patients before further training the model. However, I couldn’t find the corresponding implementation in the provided `extract_features.py` script.

Could you kindly clarify how this pretraining process was implemented in the code? Specifically:
1. Was this achieved by analyzing each WSI file individually in batches?
2. Or were the WSIs combined into a unified dataset for feature extraction?

Any insights or pointers would be greatly appreciated. Thank you in advance for your time and support!

**Comment by jjhbw** [comment]
Hi, thank you for your interest. The self-supervised learning routine we used was similar to our [im4MEC](https://github.com/AIRMEC/im4MEC) project (but with a different model architecture). So n tiles were sampled from each WSI and combined into a single unified dataset of tile images. See the sample_tiles.py script in the im4MEC codebase. Hope this helps.
